### ISSUE TITLE
Query secondary index with attribute__contains

### ISSUE THREAD

**Issue by lalvarezguillen** [pynamodb/PynamoDB#106]
Hey! In the docs it's mentioned you can use attribute__contains to query a table. That works fine for me, but I haven't been able to replicate that success with secondary indexes.

I'm trying to do this:
    `MyModel.my_secondary_index.query(my_hash_key="my_hash_key", my_range_key___contains="my_substring")`

And I'm getting the following error: 
`"Invalid filter specified: name contains [{'S':u'l'}]`

If I do attribute__begins_with or attribute__eq it works fine. Is this a bug or is it intended? Do you think there's a way around it or a simple fix maybe? Thank you.

**Comment by AusIV** [comment]
Not the author, but I'm pretty sure this is a limitation of how Dynamo DB works.

Roughly speaking, indexes work by sorting everything as it's written to the index, and when you look something up you can find it quickly because you know where it should appear in the sorted index. This makes it easy to do __begins_with and __eq, because the index is structured to find things quickly based on the how the string sorts. Arbitrary substrings don't really work with indexes, because indexes are optimized for finding things based on the start of the string.

**Comment by jpinner-lyft** [comment]
DynamoDB restrict the comparisons that are allowed on range keys using query operations:
http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-request-KeyConditionExpression

Other comparisons require the use of a scan operation but please not that doing so will consume much more capacity since every item in the table will be accessed.
