### ISSUE TITLE
Contains filter on JSON Attribute

### ISSUE THREAD

**Issue by porterhyphenborden** [pynamodb/PynamoDB#1134]
Having trouble using a contains filter on a JSON Attribute.  If I have a model like:
```
class Workflow(Model):
    run_schedule = JSONAttribute()
```

where run_schedule looks like `{"start_date": "2022-07-15T17:44:00.000Z", "recurrence": "once"}`, should I not be able to do a contains filter using the string `"recurrence": "once"`?  I know that DynamoDB just stores this as a string, so even though I know I can't filter based on a specific key/value within `run_schedule`, I thought that I would be able to filter with a sub-string by using something like `json.dumps({"recurrence": "once"})`.  This doesn't seem to work, and I'm sure there's something about the attribute value serde that I'm not understanding/that prevents this.  Help appreciated!

**Comment by ikonst** [comment]
Can you share a code snippet?

**Comment by porterhyphenborden** [comment]
Sure, thanks--
```
filter_cond = Workflow.id.exists()
if recurrence_filter:
    filter_cond = filter_cond & Workflow.run_schedule.contains(json.dumps({'recurrence': recurrence_filter}))

results = list(Workflow.sort_by_updated_on_index.query(
            hash_key=0,
            scan_index_forward=False,
            filter_condition=filter_cond
        )
    )
```
^^^ Does not work, I can use just the filter value (ie "once") in the contains filter but was hoping this was possible to make the contains filter more specific.

**Comment by ikonst** [comment]
So it's tricky, partially because `JSONAttribute` should've never existed :)

Let's assume:
```python
m = MyModel()
m.hk = 'some_id'
m.json_attr = {"foo": "bar", "abc": "xyz"}
m.save()
```
then
```
MyModel.scan(
    filter_condition=MyModel.json_attr.contains('foo')
)
```
works because effectively `'foo'` will go through `json.dumps('foo') == '"foo"'` and and the string `'"foo"'` is contained in the string `'{"foo": "bar", "abc": "xyz"}'`.

But you say you want to be more specific.

You can try:
```python
MyModel.scan(
    filter_condition=MyModel.json_attr.contains({"foo": "bar"}),
)
```
but the string `'{"foo": "bar"}'` is contained in the string `'{"foo": "bar", "abc": "xyz"}'`:
```
{"foo": "bar"}
{"foo": "bar", "abc": "xyz"}
+++++++++++++!
             ^ mismatch
```

Finally, you can use the "escape hatch" where you provide to `contains` what's effectively a raw DynamoDB expression:
```python
MyModel.scan(
   filter_condition=MyModel.json_attr.contains({"S": '"foo": "bar"'})
)
```
This works because `'"foo": "bar"'` is contained in `'{"foo": "bar", "abc": "xyz"}'`:
```
 "foo": "bar"
{"foo": "bar", "abc": "xyz"}
 ++++++++++++
```
Of course this is merely a naive string match, it's not a structural match.

Ultimately, prefer `MapAttribute` for new models. `JSONAttribute` shouldn't be used for new code.
