### ISSUE TITLE
Why MapAttribute is required for ListAttribute?

### ISSUE THREAD

**Issue by leejaedus** [pynamodb/PynamoDB#261]
I think `ListAttribute` could get common`Attribute` like `UnicodeAttribute`
But it couldn't.

On pynamodb/attributes.py#L560-563
```python
        if of:
            if not issubclass(of, MapAttribute):
                raise ValueError("'of' must be subclass of MapAttribute")
            self.element_type = of
```

And so on, in this document section, http://pynamodb.readthedocs.io/en/latest/attributes.html#list-attributes

```python
from pynamodb.attributes import ListAttribute, NumberAttribute, UnicodeAttribute

class Office(Model):
    class Meta:
        table_name = 'OfficeModel'
    office_id = NumberAttribute(hash_key=True)
    employees = ListAttribute(of=UnicodeAttribute)
```

I wanna know what a right intent is. Thanks

**Comment by gliv** [comment]
I'm running into the same issue and would be happy to see an example around `ListAttribute` that I could play with. 

Additionally, if I don't enforce the type with "of" (which should be possible according to the docs), I get a `Invalid attribute value type` (PutError, ValidationException). So obviously ListAttribute doesn't seem to work the way I would imagine (which is totally possible ;-) ). 

For something called ListAttribute, like in the example:

```
class Office(Model):
    class Meta:
        table_name = 'OfficeModel'
    office_id = NumberAttribute(hash_key=True)
    employees = ListAttribute(of=UnicodeAttribute)
```
Since the docs don't tell me otherwise, I would expect to be able to use it like a list, maybe something like:

```
ny_office = Office(3, employees=['John', 'Mike', 'Frank'])
ny_office.save()
```
Unfortunately that's not working for me. And probably I am missing something.

@jonathonlui and @jmphilli you looked into de/serializing with the right attribute type in PR [#254](https://github.com/pynamodb/PynamoDB/pull/254), you seem savvy on this, maybe you guys can help us out?

**Comment by jmphilli** [comment]
Ya this is my bad. Let me take a look

**Comment by leejaedus** [comment]
Could you give me a chance to fix that?

#281

**Comment by jmphilli** [comment]
`of` is not required.
the doc is incorrect.

[here](https://github.com/pynamodb/PynamoDB/blob/0b3349d5d2b1b646c2889524516624eb51a01249/pynamodb/tests/test_model.py#L3001) is a raw (untyped) list attribute example.

I updated the docs [here](https://github.com/pynamodb/PynamoDB/pull/282)

**Comment by leejaedus** [comment]
Um...
So if I need UnicodeAttribute Type Restriction, should I use raw (untyped) list attribute?

**Comment by jmphilli** [comment]
yes, currently. we're working on adding the type check for non map attributes.

**Comment by leejaedus** [comment]
Okay, I will try to make non-map attribute type restriction possible

**Comment by jpinner-lyft** [comment]
addressed in https://github.com/pynamodb/PynamoDB/pull/833
