### ISSUE TITLE
New Model Instance Does Not Reset Set Data

### ISSUE THREAD

**Issue by jl-DaDar** [pynamodb/PynamoDB#334]
I am seeing a very strange issue.

I have this model that has just keys and a unicode set attribute

```
class TestModel(Model):
    class Meta:
        table_name = "TestModel"
        host = "http://localhost:8000"
    modelhash= UnicodeAttribute(hash_key=True)
    modelrange = UnicodeAttribute(range_key=True)
    modelset = UnicodeSetAttribute(default=set())

TestModel('a','b').modelset.add('somevalue')

TestModel('c',d').modelset

```

I create 2 complete different instance of a model. When the second model instantiates, its modelset attribute value would already contain 'somevalue' in its set. Am I the only one experiencing this? 

seems like it only occurs to set data not unicodeattribute, have not try other type of attributes.

**Comment by jl-DaDar** [comment]
looks like the problem is caused by modelset's default being a set instead of a list. This does not make any sense as the attribute IS SUPPOSE TO BE a set, not a list. The example code on github also use list when initializing the attribute. This does not make sense at all. 

If I were to set default=[], then the model would behave more normal. However, when I instanciate the model modelset will return an empty list and I will have to make extra effort to convert it into a set and or make sure no duplicate is in the list before save, or it will give me duplicate error.

If I were to GET the item from the model table, modelset would then return a set and not a list this time.
So strange that it would accept a list as input and return a set on get. 

What is the correct way to handle this? Seem like a huge design problem.

**Comment by jpinner-lyft** [comment]
@jl-DaDar This is actually a common "gotcha" in Python and isn't specific to PynamoDB.

The default value you are setting for `modelset` is mutable. The call to `add('somevalue')` is changing the default value which is why you are seeing that change reflected in the next TestModel.

The difference in behavior between UnicodeAttribute and UnicodeSetAttribute is actually the difference between immutable strings and mutable sets.

While this is certainly surprising behavior if you've never seen it before, it is in keeping with how Python treats function arguments. See http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments for more details.

**Comment by wobeng** [comment]
@jl-DaDar what was the solution to this?

**Comment by jl-DaDar** [comment]
don't initialize it during declaration.
initialize it in init or something.

> @jl-DaDar what was the solution to this?
