### ISSUE TITLE
Random query errors on pynamodb 3.1.0

### ISSUE THREAD

**Issue by andremilk** [pynamodb/PynamoDB#366]
I get random errors while doing simple queries on a table from pynamodb models.py module.

> 
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/lib/python2.7/site-packages/connexion/decorators/decorator.py", line 118, in wrapper
>     response_container = function(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/connexion/decorators/validation.py", line 294, in wrapper
>     return function(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/connexion/decorators/produces.py", line 100, in wrapper
>     response = function(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/connexion/decorators/decorator.py", line 98, in wrapper
>     operation_handler_result = function(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/connexion/decorators/parameter.py", line 161, in wrapper
>     return function(*args, **kwargs)
>   File "/app/foo/controllers/team.py", line 188, in team_load
>     for t in teams:
>   File "/usr/lib/python2.7/site-packages/pynamodb/models.py", line 647, in query
>     for item in data.get(ITEMS):
> TypeError: 'NoneType' object is not iterable
> 

teams = Foo_TeamUser.query(slug, account.username) this is the query of which I try to iterate.

I've added a print statement just before the line which raises this exception like this:

```
       if not data.get(ITEMS):
            print '\n\n'
            print 'failed with data: {}'.format(data)
        for item in data.get(ITEMS):

```

which gives me this 

> failed with data: {u'Count': 0, u'ScannedCount': 1, u'ConsumedCapacity': {u'TableName': u'Foo_TeamUser', u'CapacityUnits': 0.5}}

the odd thing is that I found this other instance where my prints were shown but:

> failed with data: {u'Count': 0, u'Items': [], u'ScannedCount': 0, u'ConsumedCapacity': {u'TableName': u'Foo_Invite', u'CapacityUnits': 0.5}}

this one actually doesn't raise the exception

**Comment by jpinner-lyft** [comment]
The DynamoDB documentation states that the response to a query contains an "Items" array:
http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-response-Items

In your first example, this response parameter appears to be missing. The exception is being raised because PynamoDB assumes a well-formed response. If this is continuing to happen we should escalate the issue to Amazon (this would be a bug in DynamoDB itself).

In your second example, the response parameter exists but is empty (indicating no items match the query). This is a valid response and should not raise an exception. Your print statement is being executed because an empty list is considered False in python. To prevent printing these cases, replace `if not data.get(ITEMS):` with `if data.get(ITEMS) is None:`

**Comment by jpinner-lyft** [comment]
Is it possible you are doing a `count()` request (or setting `select = 'COUNT'`)?

**Comment by andremilk** [comment]
Actually the problem seems to be resolved once we renamed our indexes across the tables not to be the same, for instance we had tables A and B and both had indexes named xpto-index.
After we changed this so it would be something like Axpto-index and Bxpto-index this error didn't occur anymore.

Thanks for the tip on `if ITEMS not in data`, I will keep that in mind!

**Comment by andremilk** [comment]
OK, The error actually persisted but in a way that we didn't see it very often.
And yes, there's a count() request involved, any tips?
