### ISSUE TITLE
ListAttribute has old values from previous instance 

### ISSUE THREAD

**Issue by mcheung610** [pynamodb/PynamoDB#384]
Do you know why this example `user2` has the value from `user`?

One of my unit test was failing in this similar situation. I wonder if I am doing something wrong here. I verified if I only have a MapModel, everything is fine. This bug seems to occur only when there is a list of map of a list of map in the mapping.

```
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute, ListAttribute, MapAttribute

class AnotherMapModel(MapAttribute):
    foo = UnicodeAttribute()

class MapModel(MapAttribute):
    list_of_another_map = ListAttribute(default=[], of=AnotherMapModel)

class UserModel(Model):
    """
    A DynamoDB User
    """
    class Meta:
        table_name = 'dynamodb-user'
        region = 'us-west-1'
    email = UnicodeAttribute(hash_key=True)
    first_name = UnicodeAttribute()
    last_name = UnicodeAttribute()
    list_of_map = ListAttribute(default=[], of=MapModel)


user = UserModel()
user.list_of_map.append(MapModel(list_of_another_map=[AnotherMapModel(foo='bar')]))

user2 = UserModel()
user2.list_of_map[0].list_of_another_map[0].foo
Out[34]: 'bar'
```

**Comment by jpinner-lyft** [comment]
The issue here is with your default values:
`list_of_map = ListAttribute(default=[], of=MapModel)`
`list_of_another_map = ListAttribute(default=[], of=AnotherMapModel)`

In python function arguments are only evaluated once, so you are in sharing the same list instance between all model instances.

What you need is:
`list_of_map = ListAttribute(default=list, of=MapModel)`
`list_of_another_map = ListAttribute(default=list, of=AnotherMapModel)`

See http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments for more details.
