### ISSUE TITLE
using pynamodb with localstack

### ISSUE THREAD

**Issue by jney** [pynamodb/PynamoDB#512]
hello, i'm trying to use `pynamodb` with `localstack` but i'm currently having the following error:

```
pynamodb.exceptions.TableError: Unable to describe table: Unable to load data for: endpoints
```

I'm setting it up like this:

```python
if os.getenv("LOCALSTACK_HOSTNAME", False):
    DYNAMODB_ENDPOINT = "http://" + os.getenv("LOCALSTACK_HOSTNAME") + ":4569"

class SessionItem(Model):
    class Meta:
        host = DYNAMODB_ENDPOINT
        region = AWS_REGION
        table_name = TABLE_NAME
```

does someone have any experience using pynamodb with localstack?

**Comment by numberoverzero** [comment]
Since localstack should be on localhost, have you tried hardcoding the host value to `http://localhost:4569`?  That would eliminate env var problems across processes.


As someone else that tried use local stack, heads up that they're collecting metrics including table names: https://github.com/localstack/localstack/issues/728.  No response for 2 months.

**Comment by timboring** [comment]
@jney I'm using pynamodb with localstack for a work project. first question: is `$LOCALSTACK_HOSTNAME` getting set in the shell before you start up a python shell or the app itself?

a slightly different way to do this that ensures it'll get set to a sane default is this:

```py
DYNAMODB_ENDPOINT = os.getenv('DYNAMODB', 'http://localhost:4569')
```

As @numberoverzero mentioned, since localstack is running on `localhost`, there isn't really a need to factor it out as a separate env var.

**Comment by jney** [comment]
@timboring yes i had `LOCALSTACK_HOSTNAME` 
for some reason it works now
