### ISSUE TITLE
[pylint] R0903:Too few public methods (0/2)

### ISSUE THREAD

**Issue by xliiauo** [pynamodb/PynamoDB#548]
Hi, I'm trying to use pyndamodb in my project. But I'm always getting the `pylint R0903:Too few public methods` warning. Shall I use a namedtuple to replace the class definition if it is only used to store attribute values like `table_name`? Many thanks.

**Comment by fbidu** [comment]
Well, PyLint warnings are more of a stylistic issue. If you don't care about having too few public methods, you can just disable this warning [in many different ways](https://docs.pylint.org/en/1.6.0/faq.html#message-control).

But please take in consideration that those stylistic warnings - as boring as they might seem - they may point you to "smells" in your code. If you're facing a too few public methods warning, by example, it may be an indicator that using a full-blown class to handle your case of use is an overkill and yes, a named tuple might do a better job!

That said, I don't think this issue is related to PynamoDB and it should be closed.

All the best

**Comment by peterhchen** [comment]
There is another way without changinh your puython code:
In the ~/.pylintrc, In the [DESIGN] section, change the "min-public-methods=2" to min-public-methods=0" as below:
# Minimum number of public methods for a class (see R0903).
min-public-methods=0
