### ISSUE TITLE
Support storing empty strings

### ISSUE THREAD

**Issue by nshgraph** [pynamodb/PynamoDB#597]
An empty (but present) string is a different value to a non existent value.

Current behaviour serializes strings to None which then breaks if, for example, you want to store an empty string.

Perhaps this is expected behaviour but I couldn't find any documentation supporting this?

Thanks

**Comment by jpinner-lyft** [comment]
DynamoDB cannot store empty strings.

**Comment by nshgraph** [comment]
Thanks, and sorry for the noise. I'll have to find a different solution.

**Comment by internetofjames** [comment]
@jpinner-lyft perhaps the documentation has changed since you commented, but I am confused. I believe I am running into a similar problem as @nshgraph . I am trying to save an item to a table that has a map attribute. Within the map there is a string attribute that has an empty string as a value. When trying to save, PynamoDB replies with a PutError:
`An error occurred (ValidationException) on request _(request)_  on table _(table)_ when calling the PutItem operation: Supplied AttributeValue is empty, must contain exactly one of the supported datatypes`

[https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-attributes](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-attributes) says:

> Attribute Values
> Empty String and Binary attribute values are allowed, if the attribute is not used as a key attribute for a table or index. Empty String and Binary values are allowed inside Set, List, and Map types.

... which is precisely what I am doing.

**Comment by jpinner-lyft** [comment]
@internetofjames dynamodb introduced support for empty non-key string and binary values in May 2020
https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-dynamodb-now-supports-empty-values-for-non-key-string-and-binary-attributes-in-dynamodb-tables

**Comment by jpinner-lyft** [comment]
@garrettheel now that dynamo supports this, should we reopen this issue as a feature request?

**Comment by garrettheel** [comment]
@jpinner-lyft yep, re-opened

**Comment by jpinner-lyft** [comment]
addressed in https://github.com/pynamodb/PynamoDB/pull/830
