### ISSUE TITLE
list_iterator doesn't have last_evaluated_key object

### ISSUE THREAD

**Issue by KashishGoel** [pynamodb/PynamoDB#676]
Trying to get the last_evaluated_key returns this error: `'list_iterator' object has no attribute 'last_evaluated_key'"`

The code trying to access it matches what the docs say. So not quite sure what's going on.
```
        last_evaluated_key = None
        started = False

        while not started or last_evaluated_key:
            started = True
            results = Model.query(hash_key=hash_key,
                                             limit=10,
                                             last_evaluated_key=last_evaluated_key,
                                             rate_limit=10)
            for item in results:
                ...
            last_evaluated_key = results.last_evaluated_key
```

PynamoDB version: `4.0.0b2`

**Comment by ikonst** [comment]
I've tried this and it seems to work for me. Can you try reproducing it locally?

**Comment by wobeng** [comment]
@ikonst I have a similar problem but my return None

**Comment by garrettheel** [comment]
@KashishGoel's issue is related to other application logic changing the `ResultIterator` into a `list_iterator`.

@wobeng I'd guess that the value is legitimately `None` because you've consumed all of the items.

See: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html

> If LastEvaluatedKey is empty, then the "last page" of results has been processed and there is no more data to be retrieved.

Note that `ResultIterator` is a view over all results, not a single page.
