### ISSUE TITLE
Condition and Action should be equatable

### ISSUE THREAD

**Issue by ikonst** [pynamodb/PynamoDB#794]
`Condition` and `Action` should have an `__eq__` to make it possible to write test assertions.

**Comment by jpinner-lyft** [comment]
Tried to take an initial pass at this and quickly ran into an issue to think about:

In order to make `Condition` or `Action` equitable, we need to be able to compare their operands. For `Path` operands that means being able to write code like `Path('foo') == Path('bar')`; however, that comparison results in a `Condition` not a boolean in order to support code like `MyModel.foo == MyModel.bar`. Catch-22?

We can certainly hack something to avoid the equality comparison using __eq__ and instead compare the internal path segments but this at least sheds some light on why we didn't do this initially.

(Another option that avoids comparing operands is to first serialize the expressions and check if the serialized expression match.)

**Comment by ikonst** [comment]
We can perhaps compare their `__repr__` or serialized strings, or perhaps we can add a `_real_eq` to Operand and call that instead.
