### ISSUE TITLE
Handling intermittent TransactionInProgressException

### ISSUE THREAD

**Issue by navels** [pynamodb/PynamoDB#808]
Our application will occasionally encounter this exception when committing a transaction.  For example:

`Failed to write transaction items An error occurred (TransactionInProgressException) on request (F5HO7TOH9T3P4TA258Q3OVVASFVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (None) when calling the TransactWriteItems operation`

Note: we are not supplying the transaction with any kind of request token.

It's not clear to me how we should handle this.  I'm guessing it happens when boto retries a transaction after a network error.  Perhaps we need to supply a client request token and handle retries ourselves?  I'm assuming that once the transaction is committed at the db that attempts to commit the transaction again with the same client request token will succeed . . . ?

**Comment by ikonst** [comment]
From [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.transact_write_items):
> ClientRequestToken (string) --
> Providing a ClientRequestToken makes the call to TransactWriteItems idempotent, meaning that multiple identical calls have the same effect as one single call.
> ...
> This field is autopopulated if not provided.

At the same time, [boto3 docs on retries](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html#standard-retry-mode) also say `TransactionInProgressException` is one of the exception types that'd be automatically retried.

Maybe it was the case that:
- call failed with e.g. a timeout while it was actually executed by the server
- (boto3) retry failed since that transaction was already in progress
- (boto3) retry failed since that transaction was still in progress
(up to max retries)

I'm not very familiar with DynamoDB transactions. @hallie, have you seen similar things?

**Comment by hallie** [comment]
boto3 supplies their own client request token for a transaction if its missing (the `(F5HO7TOH9T3P4TA258Q3OVVASFVV4KQNSO5AEMVJF66Q9ASUAAJG)` value included in your error log). Still unsure if that's a good call on their part, given that they also automatically retry on those failures

I would suggest trying to pass in your own value for that and see what happens

**Comment by navels** [comment]
Thanks, I was leaning towards trying that next.  Will report back!

**Comment by ikonst** [comment]
I think it's a sensible decision on their part, since they do assign it before their retry logic so that makes their retries idempotent and that's better than not doing it.

**Comment by ikonst** [comment]
(I know it's not our responsibility but maybe we should note in our docs that the client request token is autopopulated by boto3.)

**Comment by navels** [comment]
We finally got around to implementing this (providing our own request token and retrying) and it fixed the problem.  We hit this failure 63 times over the last week.  Using a linear retry with 5-second delay, the transaction succeeded after 1 retry 54 times.  It took 2 retries 8 times.  The remaining case took 10 retries (so 50 seconds . . . yikes) but eventually went through.
