### ISSUE TITLE
How to query only with the KeyConditionExpression

### ISSUE THREAD

**Issue by jnoortheen** [pynamodb/PynamoDB#812]
I am trying to query with the hash_key value. If I pass a condition expression of the hash_key it returns the error below

![image](https://user-images.githubusercontent.com/6702219/87423469-fcf91e00-c5f7-11ea-893f-48d57fd43ccf.png)

is it possible to query like this ?

![image](https://user-images.githubusercontent.com/6702219/87423522-14d0a200-c5f8-11ea-9df5-2e637118c4f4.png)

I don't find any info on KeyConditionExpression from docs.

**Comment by jnoortheen** [comment]
seems like other conditional operators are not supported on hash_key.

**Comment by ikonst** [comment]
Yeah,  the first argument to `query` is a hash key, not a condition, DynamoDB doesn't support conditional operators on hash keys since a hash key is a way to pick a DynamoDB shard: if you could do conditions on them, then you'd effectively have to "scan" across all your shards, negating the performance benefits of DynamoDB.

You can create a GSI if you need to do conditional queries over hash keys. Ideally the hash key could be a range key in that GSI and your conditions would be the kind of conditions that are permissible on a range key (AKA sort key) -- see the DynamoDB docs.

**Comment by jnoortheen** [comment]
Yes now I have understood. It is actually a global secondary index that I am querying.
