### ISSUE TITLE
Documentation severely lacks READ operation examples

### ISSUE THREAD

**Issue by alivcor** [pynamodb/PynamoDB#820]
Have been trying to use this library, and I am surprised to find so much documentation on Update/Delete/Insert but None to Zero documentation on READING from the database. Does it even support reading?

**Moreover the only example on the README further confuses the reader:**

  Now, search your table for all users with a last name of 'Denver' and whose
    first name begins with 'J':

    for user in UserModel.query("Denver", UserModel.first_name.startswith("J")):
        print(user.first_name)

When you're defining the UserModel, you specify `lastName` as the third attribute (in ordering) - how would the library automatically know "Denver" is supposed to be the lastName ?

    from pynamodb.models import Model
    from pynamodb.attributes import UnicodeAttribute

    class UserModel(Model):
        """
        A DynamoDB User
        """
        class Meta:
            table_name = "dynamodb-user"
        email = UnicodeAttribute(null=True)
        first_name = UnicodeAttribute(range_key=True)
        last_name = UnicodeAttribute(hash_key=True)

**A logical way would be:**

    for user in UserModel.query(UserModel.last_name.equals("Denver"), UserModel.first_name.startswith("J")):
        print(user.first_name)

**Comment by garrettheel** [comment]
Yes, the library does support reading items. There are various docs that provide examples of how to do this already. I'm sure we could do a better job of providing documentation examples, and I'd definitely welcome PRs attempting to do so.

The auto-generated [API docs](https://pynamodb.readthedocs.io/en/latest/api.html) and tests in this repo also provide many examples of using the library.

> When you're defining the UserModel, you specify lastName as the third attribute (in ordering) - how would the library automatically know "Denver" is supposed to be the lastName ?

The order of the attributes is irrelevant. `UserModel.query("Denver")` refers to the `last_name` because `last_name` is the hash key. Only one attribute can be specified as the hash key.

**Comment by alivcor** [comment]
Thanks @garrettheel - closing this issue !
