### ISSUE TITLE
get_or_create method

### ISSUE THREAD

**Issue by mhihasan** [pynamodb/PynamoDB#888]
I would like to contribute to add `get_or_create` method on PynamoDB Model.
```python
Model.get_or_create(hash_key, range_key, **kwargs)
```
@jlafon what do you think about this addition?

**Comment by ikonst** [comment]
Can you detail what you'd want it to do especially in terms of API operations?

**Comment by hasanul23** [comment]
At first, I will get an item calling `GetItem` from DB passing hash_key and range_key(optionally). If no item exists, I will create a record by calling `PutItem`.

**Comment by hasanul23** [comment]
@ikonst Should I proceed to this feature?

**Comment by ikonst** [comment]
Sorry for taking a while to respond. I wanted to look up precedent -- specifically as I recalled mongoengine (a MongoDB ORM) had a similar method ('get_or_create') and they decided it since it was impossible to implement consistently. I wanted to check whether DynamoDB would fall under the same category. By the way, I think it's OK for individual users to pick how much they care about consistency but we should be careful about what we introduce to the library since users might get a false sense of "safety" if something is built into the library.

If you make the `PutItem` conditional on the item not existing, then perhaps this could be done atomically in DynamoDB -- roughly like this:
```python
def get_or_create(hk, rk):
    """
    Note: Might raise PutError with ConditionalCheckFailedException
    """
    try:
      item = cls.get(hk, rk)
    except cls.DoesNotExist:
      item = cls()
      item.hash_key = hk
      item.range_key = rk
      item.save(condition=cls.hash_key.does_not_exist() & cls.range_key.does_not_exist())

    return item
```

A separate question I'd have is - why? Typically when I implement an operation in a CRUD app that has "get_or_create" semantics, it's because I'm trying to persist something, e.g.
```python
def set_shopping_cart_contents(user_id, products):
    try:
      shopping_cart = ShoppingCart.get(user_id)
    except ShoppingCart.DoesNotExist:
      shopping_cart.user_id = user_id
      shopping_cart.created_at = now()

    shopping_cart.products = products
    shopping_cart.save()
```
so since I need to `save` in both cases, an initial `get_or_create` would result in an extra PutItem that I don't have to perform (and be billed for).

@garrettheel @jpinner-lyft wdyt?

**Comment by hasanul23** [comment]
Hi, what about this proposal?

**Comment by ikonst** [comment]
@hasanul23 can you help illustrate the "why"?

**Comment by hasanul23** [comment]
At my day to day work using PynamoDB, I often need to do operation like, get an item from table.If the item does not exist, create item with given attributes. 
To solve this, currently I am writing try..except block everywhere I need this logic. So, I am feeling the absence of `get_or_create`(django has this method). I think it would be a great addition to this package.

**Comment by ikonst** [comment]
@hasanul23 Can you give a more complete example? I find that in our applications, whenever we "get or create" in the same code path, it's usually GetItem -> initialize/mutate -> PutItem.

**Comment by hasanul23** [comment]
Suppose, In a system, user can order a user can order without logging in, just by entering email. In that case, the User might be not in the system DB initially.
Current approach is:
```python
try:
     user = User.get(email)
except User.DoesNotExist:
     user = User(email)
     user.name = "John Doe"
     user.save()

order = Order(order_id)
order.user_id =user.id
order.save()
```

My expectation is:

```python
user = User.get_or_create(email, name="John Doe")

order = Order(order_id)
order.user_id =user.id
order.save()
```

**Comment by ikonst** [comment]
Ahh, I see. This makes sense.

If I had to do this in a helper method, it'd be something like: 
```python
def get_or_create(model: Type[Model], hk: Any, rk: Optional[Any] = None, **attributes: Any) -> Model:
    """
    Note: Might raise PutError with ConditionalCheckFailedException
    """
    try:
      return model.get(hk, rk)
    except model.DoesNotExist:
      item = model(hk, rk, **attributes)
      condition = model._hash_key_attribute().does_not_exist()
      rk_attr = model._range_key_attribute()
      if rk_attr:
          condition &= rk_attr.does_not_exist()
      item.save(condition=condition)
      return item
```
