### ISSUE TITLE
How to implement condition on Hash key

### ISSUE THREAD

**Issue by ShivamSharma11** [pynamodb/PynamoDB#894]
How to implement begin with on hash key?

**Comment by ikonst** [comment]
You can't, since it's used for sharding:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.CoreComponents.html

If you don't need sharding, then have a hash key that's a constant and use a range key to scan, but then you probably don't need DynamoDB since you don't really expect to scale.
