### ISSUE TITLE
JSONAttribute(default={}) will be referenced across all the created objects

### ISSUE THREAD

**Issue by biniow** [pynamodb/PynamoDB#961]
Looks like there is a classic bug of mutable default value in JSONAttribute. Please check the following:
```
from pynamodb.attributes import JSONAttribute
from pynamodb.models import Model


class TestModel(Model):
    misc = JSONAttribute(default={})


if __name__ == '__main__':
    a = TestModel()
    a.misc['a'] = 1

    b = TestModel()
    print(b.misc)
```
the output is
```
{'a': 1}
```
while as an end user I should expect to have an empty dict there. 

There is an easy workaround where we can use `default=dict` and this does the trick, but it should be explicitly mentioned in the documentation https://pynamodb.readthedocs.io/en/latest/api.html#pynamodb.attributes.JSONAttribute

Ultimately I think that mutable default arguments should be not allowed at all to be set as a default value.

**Comment by ikonst** [comment]
This could be a good breaking change to make in PynamoDB 6 to allow only some primitive types and callables in `default`.

**Comment by garrettheel** [comment]
+1 to adding this as a breaking change in 6.0. I think it would be best to raise an exception in the cases above (not callable or an immutable primitive). For cases that really want to use a mutable value, they can just wrap in a lambda

**Comment by ikonst** [comment]
There are many built-in immutable types.

We can add this to `Attribute.__init__`:
```python
if not callable(default) and not isinstance(default, IMMUTABLE_TYPES):
   raise ValueError(...)
```

This would address the common "mutable dict/list/set" issue, but not the "callable called instead of being passed" issue.

We can either:
- exclude `datetime` from IMMUTABLE_TYPES to prevent this specific error
- rely on linters (maybe contribute a rule to https://github.com/returntocorp/semgrep-rules/tree/develop/python?)

Interestingly PEP 675 provides a type-checker way to prevent non-literals from being passed as arguments, but it's very specific to string literals.

**Comment by garrettheel** [comment]
Thanks @ikonst!
