### ISSUE TITLE
Setting <UnicodeSetAttribute>.set([]) (empty list) throws "Nonetype is not iterable" error.

### ISSUE THREAD

**Issue by hoIIer** [pynamodb/PynamoDB#962]
During an update operation a UnicodeSet field may have it's value changed back to empty e.g. []

The following code fails:
```
(Pdb) actions = []
(Pdb) actions.append(attr.set([]))
(Pdb) record.update(actions)
```
`*** TypeError: 'NoneType' object is not iterable`

The following two examples work:
```
(Pdb) actions = []
(Pdb) actions.append(attr.set(None))
(Pdb) record.update(actions)
```
```
(Pdb) actions = []
(Pdb) actions.append(attr.set(['foo', 'bar']))
(Pdb) record.update(actions)
```

Is this a bug?

**Comment by hoIIer** [comment]
@ikonst reopening as I ran into this again, is it a bug?

Feels very annoying to not be able to reset a UnicodeSetAttribute to empty in an update operation.

`instance.update(actions=[model.Thing.set_or_list.set({}|[])])` -> `*** TypeError: 'NoneType' object is not iterable`

**Comment by ikonst** [comment]
I wonder what causes this error.

For what it's worth, though, underlying dynamodb does not support empty sets:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes
so it's unclear how it would behave, e.g.
- same as unsetting (assigning None and then you read None back)
- give an error, but a clearer one

**Comment by hoIIer** [comment]
I guess the annoying part is by removing it, you have to ensure any uses of the value explicitly test for `None` versus knowing it would always be an instance of list or set

**Comment by ikonst** [comment]
I agree. Since the underlying database cannot store an empty set for us, we have to pick an alternative representation. An attribute being **unset** in the DynamoDB item manifests as `None` in the Pythonic model, so we cannot use **unset** as the representation, since it'll read back as `None`.

We could decide on a rule e.g. an empty set serializes as {"__MAGIC_PYNAMODB_VALUE_UNSET__"}, but that would be awkward.

Another compromise would be:
- `UnicodeSetAttribute(null=True)` serializes `set()` as **unset**, and reads back as `None`
- `UnicodeSetAttribute(null=False)` serializes `set()` as **unset**, and reads back as `set()`

**Comment by hoIIer** [comment]
@ikonst thank you!
