### ISSUE TITLE
Can't put `SomeModel.some_attr.exists() & (SomeModel.some_attr != None)` in `filter_condition` in queries

### ISSUE THREAD

**Issue by sricharanreddyb-delhivery** [pynamodb/PynamoDB#963]
This part of code where the `other` variable is being compared against `None` is causing the said issue.

https://github.com/pynamodb/PynamoDB/blob/2232fd43e9221024f00939e023ed8c92bca8da33/pynamodb/attributes.py#L133-L146

Can this be corrected somehow? Or do I have to do `Path(SomeModel.some_attr) != None` in the client-code?

**Comment by ikonst** [comment]
The `other is None or isinstance(other, Attribute)` check is to allow comparing attributes with `None` or other attributes outside of the context of conditional expressions. Honesty don't see the use case for that, but then again `SomeModel.some_attr != None` isn't a meaningful conditional expression either, since `None` is not a valid value for a DynamoDB attribute (except for a `NullAttribute` which is always `None`).

**Comment by sricharanreddyb-delhivery** [comment]
I had a use-case where `phone` attribute in a table is filled with values of types `string` and `None` (inserted with boto3). Needed to filter out values that are only `string`.

**Comment by ikonst** [comment]
Is it the case that an attribute's type is dynamic - sometimes it's `S` and sometimes it's `NULL`?

**Comment by sricharanreddyb-delhivery** [comment]
Yes

**Comment by ikonst** [comment]
What you're doing is a little strange from PynamoDB perspective, since we don't support attributes having variable types -- it's either an `S` or `N` or `SS` ... or a `NULL` but not two or more.

Maybe try something like this:
```python
class MyModel(Model):
   some_attr = UnicodeAttribute(null=True)
   # an alias to some_attr, allowing you to access it under a different type
   some_attr_null = NullAttribute(null=True, attr_name="some_attr")
```
and then your condition would be
```python
MyModel.some_attr.exists() && MyModel.some_attr_null == True
```
(The `True` doesn't matter since `NullAttribute.serialize` always returns `True` anyway no matter what value -- it's just a placeholder really, could've been `42`...)

Let me know if this works.

**Comment by sricharanreddyb-delhivery** [comment]
Thanks. I'll try it out.

**Comment by sricharanreddyb-delhivery** [comment]
Thanks @ikonst 
It worked.
